### ISSUE TITLE
Element Tab: Nach einem Inhaltselement Metamodels Modul wird nichts mehr im 2ten Tab angezeigt.

### ISSUE THREAD

**Issue by stu2019** [contao-themes-net/zero-one-theme-bundle#10]
Ich habe eine Metamodels Tabelle angelegt. Auf 2 Artikeln wurde jeweils ein Metamodels Modul platziert und die Ergebnisse werden angezeigt. Einmal die 7 aktuellesten Einträge, einmal ein Archiv.
Nun habe ich nach Anleitung ein Element Tab angelegt.
Mit normalen Headline Inhaltselementen wird unter beiden Tabs etwas angezeigt.
Verwende ich nun ein MetaModels Modul als Inhaltselement unter dem ersten Tab wird unter dem 2ten Tab nichts mehr angezeigt. Auch das vorher noch gezeigte Headline Element nicht mehr.
Welche weiteren Infos werden noch benötigt?

**Comment by MDevster** [comment]
Hey. Gibt es Fehler in der Browser Konsole? Hast du einen Link wo ich mir das ansehen kann?

**Comment by stu2019** [comment]
Hallo

einen Fehler sehe ich nicht.
Ich kann auch gerne telefonisch bei der Fehlerreproduktion unterstützen.

Ein Link auf die Website ist (temporär freigeschaltet.
https://dorfzeitung.s3.design/e-paper-v2.html

**Comment by stu2019** [comment]
Backend-User kann ich auch gerne zur Verfügung stellen.

Viele Grüße
Thomas

**Comment by seibtph** [comment]
Fehler wurde gelöst, ich habe bereits per Mail geantwortet.

Problem war ein fehlendes </div> in einem angepassten Template.
