### ISSUE TITLE
add the highlight style sheet for ce_code

### ISSUE THREAD

**Issue by MDevster** [contao-themes-net/zero-one-theme-bundle#15]
I think the line in  following link is missing in ce_code.html5 template

https://github.com/contao/contao/blob/9107f939c444a31ff26252179497222b9e31424d/core-bundle/src/Resources/contao/templates/elements/ce_code.html5#L6

Can be reproduced in the demo https://0.1.contao-themes.net/typografie.html

**Comment by seibtph** [comment]
fixed in version [1.7.0](https://github.com/contao-themes-net/zero-one-theme-bundle/tree/1.7.0)
