### ISSUE TITLE
Parallax on mobile phone / banner

### ISSUE THREAD

**Issue by millerc-bmf** [contao-themes-net/zero-one-theme-bundle#21]
Hi, 
I added the very nice parallax functionality on our homepage. But this doesn't work on mobile phones - I understand this issue. But the photo on Smartphones doesn't scale. Do you have any idea how to adapt this?

And: I tried to change the favicon, but it doesn't work. Any idea how to solve this issue?

BR Christian

**Comment by millerc-bmf** [comment]
Would it be possible to help me with this issue?

**Comment by MDevster** [comment]
Will be fixed in version 1.8.1. The release is scheduled for the middle of next week.

**Comment by millerc-bmf** [comment]
Hi Mathias,

is the new release published and available with this fix?

BR
Christian

**Comment by seibtph** [comment]
The parallax image is not available for iOS, because the css definition `background-image: fixed` is not supported by iOS. You can add the inserttag `{{ua::class}}` as body class in your theme layout (Expert settings -> Body class), than only the image should be displayed.

**Comment by millerc-bmf** [comment]
Hi,

many thanks for your answer. I’m not a Contao / CSS expert. Maybe you can send me some detailed information where and how to insert….?!
That would be great!

BR
Christian
