### ISSUE TITLE
Setup: web and public folder

### ISSUE THREAD

**Issue by Xirdion** [contao-themes-net/zero-one-theme-bundle#24]
Within the `ZeroOneThemeSetup` class you are using predefined paths to the css and image files to copy them into the contao-files-directory.
But you are still using the "old" web-folder to access the files. With newer contao / symfony versions the resources are in the public folder.

So instead of writing:
```php
$path = TL_ROOT . '/web/bundles/contaothemesnetzeroonetheme';
```

You could write:
```php
$path = TL_ROOT . '/public/bundles/contaothemesnetzeroonetheme';
```

As both writings could be possible, maybe checking if `web` or `public` exist, would be better.

**Comment by Xirdion** [comment]
The same issue appears in the `fe_page_0.1` template when trying to load the scss-files.
```php
$scssStr .= '@import "../../../../web/bundles/contaothemesnetzeroonetheme/scss/' . $style . '.scss";' . "\n";
```

**Comment by MDevster** [comment]
Please update to release 1.9.1.
