### ISSUE TITLE
Aktualisierung auf Contao 4.13 nicht möglich

### ISSUE THREAD

**Issue by MaAleJaPe** [contao-themes-net/zero-one-theme-bundle#26]
Pakete werden aktualisiert
composer require contao/manager-bundle=4.13.* contao/news-bundle=4.13.* contao/calendar-bundle=4.13.* contao/faq-bundle=4.13.* contao/comments-bundle=4.13.* contao/newsletter-bundle=4.13.* contao/listing-bundle=4.13.*
composer update contao/manager-bundle contao/news-bundle contao/calendar-bundle contao/faq-bundle contao/comments-bundle contao/newsletter-bundle contao/listing-bundle contao/conflicts --no-install
> Resolving dependencies using Composer Cloud v3.5.0
!!! Current server is sponsored by: terminal42 gmbh !!!
[7.4MiB/0.45s] Loading composer repositories with package information
[66.6MiB/9.25s] Updating dependencies
[100.9MiB/9.68s] Your requirements could not be resolved to an installable set of packages.
[100.9MiB/9.68s] 
  Problem 1
    - contao/manager-bundle[4.13.0, ..., 4.13.8] require symfony/filesystem ^5.4 -> found symfony/filesystem[v5.4.0, ..., v5.4.12] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires contao/manager-bundle 4.13.* -> satisfiable by contao/manager-bundle[4.13.0, ..., 4.13.8].
[100.9MiB/9.68s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[37.7MiB/9.73s] Memory usage: 37.69MB (peak: 177.09MB), time: 9.74s.
[37.7MiB/9.73s] Finished Composer Cloud resolving.
# Cloud Job ID 4HeENETgSDs0rV37GiTGte9QI7DItJxNEZYyczgEsOWOIvVIzgsdq1gEYmqZ9aAi5SogZ3WKI failed
composer install

**Comment by MDevster** [comment]
Hey @MaAleJaPe, kannst du bitte deine komplette composer.json? Von welcher Contao Version aus möchtest du aktualisieren.

**Comment by MaAleJaPe** [comment]
Hallo MDesvter
[composer.zip](https://github.com/contao-themes-net/zero-one-theme-bundle/files/9534944/composer.zip)
von Contao Version 4.12.7

**Comment by seibtph** [comment]
0.1 Isotope ist noch nicht für Contao 4.13 verfügbar. Es sollte aber nicht mehr lange dauern bis das auch funktioniert.

**Comment by MDevster** [comment]
@MaAleJaPe du solltest jetzt updaten können.
