### ISSUE TITLE
Google Fonts deactivation

### ISSUE THREAD

**Issue by millerc-bmf** [contao-themes-net/zero-one-theme-bundle#30]
Hi,
As you already know, a lot of homepages that use Google Fonts are being warned. This is also the case on my side. Is there a plugin that prevents data transfer to Google or an easy way to disable google fonts?

many Thanks Christian

**Comment by MDevster** [comment]
Hey Christian. Our themes do not load Google Fonts. It must have happened via an additional extension or by adding it manually in the layout or fe_Page. We have a tool with which we regularly check all our domains and those of our customers for possible reasons for warning. However, the tool cannot tell you where it was included, only that it is there. Google fonts can also be included via a YouTube ifame, for example, etc.
Without domain or access to the backend, it is difficult to say.

**Comment by millerc-bmf** [comment]
Many thanks for your fast and positive feedback.

Maybe you can have a look at www.bmf-2023.de <http://www.bmf-2023.de/>?!

BR
Christian

**Comment by millerc-bmf** [comment]
Many, many thanks for your great support!!!

BR
Christian

**Comment by MDevster** [comment]
Which error do you mean?

**Comment by millerc-bmf** [comment]
I attached the screenshot of the error and the error.log as ZIP…

BR
Christian

**Comment by millerc-bmf** [comment]
Hi,

how can I give my article a complete background color over the complete width?

I want to optimize our page www.bmf-2023.de <http://www.bmf-2023.de/> a little bit…

BR
Christian

**Comment by seibtph** [comment]
Hi Christian,

you can add a class to the article (e.g. article-bg) and add some css in your custom.scss:

```
.article-bg {
	position: relative;
	
	&:before {
		background: #115613;
		position: absolute;
		content: "";
		top: 0;
		left: 0;
		width: 100vw;
		height: 100%;
		left: calc(0px - ((100vw - calc(100%)) / 2));
		z-index: -1;
	}
}
```

![Startseite-0-1-Energy-Saving-Contao-Theme](https://user-images.githubusercontent.com/17127525/214535775-a631fd9c-96e3-4e47-9139-564487098525.png)

**Comment by millerc-bmf** [comment]
Sorry, but I had no success. Attached two screenshots of the css article...

Can you help me again?

BR Christian



> Am 25.01.2023 um 11:09 schrieb Philipp Seibt ***@***.***>:
> 
> 
> Hi Christian,
> 
> you can add a class to the article (e.g. article-bg) and add some css in your custom.scss:
> 
> .article-bg {
> 	position: relative;
> 	
> 	&:before {
> 		background: #115613;
> 		position: absolute;
> 		content: "";
> 		top: 0;
> 		left: 0;
> 		width: 100vw;
> 		height: 100%;
> 		left: calc(0px - ((100vw - calc(100%)) / 2));
> 		z-index: -1;
> 	}
> }
> 
>

**Comment by seibtph** [comment]
I can't see any screenshots. Can you attache the screenshot directly in the github comment or send an email to support [AT] pdir .de ?
