### ISSUE TITLE
Instalation on Contao 5.0.4 fails

### ISSUE THREAD

**Issue by olivhu** [contao-themes-net/zero-one-theme-bundle#31]
Hi
The instalation aborts with the folowing mesage:

composer update contao-themes-net/zero-one-theme-bundle contao/conflicts --no-install --no-scripts
> Resolving dependencies using Composer Cloud v3.5.1
[6.7MiB/0.15s] Loading composer repositories with package information
[60.5MiB/7.63s] Updating dependencies
[76.9MiB/7.92s] Your requirements could not be resolved to an installable set of packages.
[76.9MiB/7.92s] 
  Problem 1
    - Root composer.json requires contao-themes-net/zero-one-theme-bundle ^1.10 -> satisfiable by contao-themes-net/zero-one-theme-bundle[1.10.0].
    - contao-themes-net/zero-one-theme-bundle 1.10.0 requires contao/core-bundle ^4.4 -> found contao/core-bundle[4.4.0, ..., 4.13.12] but these were not loaded, likely because it conflicts with another require.
[76.9MiB/7.92s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[34.5MiB/7.95s] Memory usage: 34.53MB (peak: 171.06MB), time: 7.95s.
[34.5MiB/7.95s] Finished Composer Cloud resolving.
# Cloud Job ID zald4bUTpl0cw8o9jEAnXXMbpFsBeo8gsWIuvULxKXm0dJ9kDqXawnUpH3QsVXQchAeZMMr4UOnRYm2ELAoDTgrHvmRTfpMvh3O3CRUTGbuOCXt failed

Are there any workarounds to solve this error?

br

oliver

**Comment by MDevster** [comment]
A new version 2.0.0 will be release today or tomorrow. We have to adjust some twig templates before.

**Comment by olivhu** [comment]
perfect, thx in advance and best regards

oliver

Mathias Arzberger ***@***.***> schrieb am Do., 27. Okt. 2022,
05:11:

**Comment by MDevster** [comment]
Version 2.0.0 has been released. Have fun updating or testing!

**Comment by olivhu** [comment]
thx have a nice weekend

br

oliver

Mathias Arzberger ***@***.***> schrieb am Sa., 29. Okt. 2022,
16:09:

**Comment by olivhu** [comment]
Installation succesful

 

there is still a problem with the "initial demo data migration" which isnt working, see the attached the screenshot.

 

Br

 

Oliver

 



 

Oliver H < ***@***.***> ***@***.***> schrieb am Do., 27. Okt. 2022, 13:19:

perfect, thx in advance and best regards

 

oliver

 

Mathias Arzberger < ***@***.***> ***@***.***> schrieb am Do., 27. Okt. 2022, 05:11:

A new version 2.0.0 will be release today or tomorrow. We have to adjust some twig templates before.
