### ISSUE TITLE
Adressdaten mandatory

### ISSUE THREAD

**Issue by MaAleJaPe** [contao-themes-net/zero-one-theme-bundle#36]
Die Felder in Adressdaten: Strasse, PLZ und Ort sollten mandatory sein. Wie kann ich das ändern?

**Comment by seibtph** [comment]
Du legst im Contao Root unter contao/dca eine tl_member.php mit folgendem Inhalt an:

```
<?php

$GLOBALS['TL_DCA']['tl_member']['fields']['street']['eval']['mandatory'] = true;
$GLOBALS['TL_DCA']['tl_member']['fields']['postal']['eval']['mandatory'] = true;
$GLOBALS['TL_DCA']['tl_member']['fields']['city']['eval']['mandatory'] = true;
```

Und anschließend den Cache leeren. Dann sollte das funktionieren.

**Comment by MaAleJaPe** [comment]
Vielen Dank
