### ISSUE TITLE
Anpassung für form_password.html5 führt zu Fehlermeldung

### ISSUE THREAD

**Issue by stu2019** [contao-themes-net/zero-one-theme-bundle#38]
Die in der Dokumentation aufgeführte Anpassung für Formulare im form_password.html5 führt zu einer Fehlermeldung.

Siehe auch: https://community.contao.org/de/showthread.php?81701-Fehler-in-Modul-quot-Personendaten-quot-Passwort

Es wurde wohl ab Contao 4.12 nur noch 1 Passwortfeld verwendet?

So sollte es dann ab 4.12 stimmen?:
<?php $this->extend('form_row'); ?>

<?php $this->block('field'); ?>
  <?php if ($this->hasErrors()): ?>
    <p class="error"><?= $this->getErrorAsString() ?></p>
  <?php endif; ?>

  <input type="<?= $this->type ?>" name="<?= $this->name ?>" id="ctrl_<?= $this->id ?>" class="text<?php if ($this->hideInput): ?> password<?php endif; ?><?php if ($this->class): ?> <?= $this->class ?><?php endif; ?>" value="<?= Contao\StringUtil::specialchars($this->value) ?>"<?= $this->getAttributes() ?><?php if ($this->label): ?> placeholder="<?= $this->label ?><?php if ($this->mandatory): ?> *<?php endif; ?>"<?php endif; ?>>
<?php $this->endblock(); ?>

**Comment by seibtph** [comment]
Ist in Dokumentation geändert worden
