### ISSUE TITLE
no shop menu

### ISSUE THREAD

**Issue by MaAleJaPe** [contao-themes-net/zero-one-theme-bundle#5]
After two local installations, it is not possible to see the menu "Shop". 
![Screenshot 2020-09-19 190005](https://user-images.githubusercontent.com/16896819/93672370-a18d5580-faaa-11ea-84bd-0b525c462511.png)

**Comment by seibtph** [comment]
Have you installed the 0.1 Theme Bundle or 0.1 Isotope Bundle? You should buy a license to install the 0.1 Isotope Shop Demo: https://contao-themes.net/theme-detail/zeroone-isotope.html.

**Comment by MaAleJaPe** [comment]
wie können Sie the issue schliessen, ohne Ihre Eingangszahlungen zu berücksichtigen?

**Comment by MaAleJaPe** [comment]
Ja, das habe ich gemacht

 

 

Von: Philipp Seibt <notifications@github.com> 
Gesendet: Montag, 21. September 2020 09:49
An: contao-themes-net/zero-one-theme-bundle <zero-one-theme-bundle@noreply.github.com>
Cc: MaAleJaPe <a.pedraza@bluewin.ch>; Author <author@noreply.github.com>
Betreff: Re: [contao-themes-net/zero-one-theme-bundle] no shop menu (#5)

 

Have you installed the 0.1 Theme Bundle or 0.1 Isotope Bundle? You should buy a license to install the 0.1 Isotope Shop Demo: https://contao-themes.net/theme-detail/zeroone-isotope.html.

**Comment by MDevster** [comment]
Hallo @MaAleJaPe, leider gab es hier wohl ein kleines Kommunikationsproblem bei uns im Haus. Natürlich prüfen wir die Installation unter Windows mit Laragon noch einmal.
