### ISSUE TITLE
Question | Bug | Feature - Placement of $this->head

### ISSUE THREAD

**Issue by tarun-uwe** [contao-themes-net/zero-one-theme-bundle#6]
Hello contao-themes-net Team, 

I had the problem, that terminal42/fineuploader was not working with your theme. I tried different things, but could not figure out why. Today I wanted to add my own <meta> Tags to TL_HEAD, which were added to the `<body>` instead to the `<head>`.

I checked the fe_page template and found that you include the `$this->head` in `<body>`Tag.
I'm not sure if that is a feature or a bug. There are some Bundles which want to add, JavaScript or Meta Tags to the `head` element.

https://github.com/contao-themes-net/zero-one-theme-bundle/blob/8e51d700c18f144aaf14800c9bb391980b97bca3/src/Resources/contao/templates/frontend/fe_page_0.1.html5#L50

vs.

Original [fe_page](https://github.com/contao/core-bundle/blob/483d930b3d84bc9884273d664c29a900242be759/src/Resources/contao/templates/frontend/fe_page.html5#L20) of Contao

Best regards Uwe

**Comment by seibtph** [comment]
Yes, this is not the correct position for $this->head. In the theme version 1.2.7 I have moved $this->head into the head.
