### ISSUE TITLE
Parallax nicht auf ganzer Breite

### ISSUE THREAD

**Issue by jonasjoyless** [contao-themes-net/zero-one-theme-bundle#7]
Hi!
Ich habe die Einstellungen für das Parallax-Element, wie in der Dokumentation angegeben, übernommen. (Wie im Screenshot zu sehen)
Allerdings wird es mir im Frontend nicht auf der vollen Breite der Website angezeigt (zweiter Screenshot), wie es eigentlich auf der Demo-Website zu sehen ist.
Wo könnte mir ein Fehler unterlaufen sein?

Vielen Dank für die Hilfe!

Gruß,
Jonas

![Bildschirmfoto 2020-10-20 um 11 56 05](https://user-images.githubusercontent.com/73168192/96571953-8e012480-12cc-11eb-88b6-0ecc61ea5cd0.png)

![Bildschirmfoto 2020-10-20 um 11 56 35](https://user-images.githubusercontent.com/73168192/96571918-83df2600-12cc-11eb-8757-b90d3e9eb6c5.png)

**Comment by seibtph** [comment]
Hallo Jonas,

die CSS-Klassen müssten bei dem Artikel in den Artikeleinstellungen eingefügt werden und nicht beim Inhaltselement selbst. Dann müsste es funktionieren.

**Comment by jonasjoyless** [comment]
Vielen Dank! Das war tatsächlich mein Fehler.

Gruß,
Jonas
