### ISSUE TITLE
import template

### ISSUE THREAD

**Issue by Ernestopheles** [contao-themes-net/zero-one-theme-bundle#8]
Moin,

habe nach Anleitung versucht, das template zu contao 4.10 (voll) zu importieren, den Haken bei "Tabelle nicht leeren" gesetzt.
Es gibt einen sql Error SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'.

Kann es sein, dass der Haken nicht gesetzt werden darf? Das läuft jedenfalls sauber durch, muss dann aber einiges erneut anlegen...

Danke und liebe Grüße, Ernst

**Comment by seibtph** [comment]
Ich habe es eben nochmal mit der neuesten Version getestet und da hat es ohne Probleme funktioniert.

Ich schätze mal, dass die Datenbank nicht komplett leer war und dadurch der Fehler zu Stande kam. Das Häkchen sollte man nur setzen, damit der Benutzer nicht direkt wieder gelöscht wird.
