### ISSUE TITLE
custom.scss

### ISSUE THREAD

**Issue by millerc-bmf** [contao-themes-net/zero-one-theme-bundle#9]
Hi,
I use the contao theme "01. Theme" and want to change some settings in the custom.scss and _custom_variables.scss, but the changes are not available at the homepage...

Do you have any idea?
Below the link to the page: https://www.bmf-2022.de

And here the code for custom.scss:
.form-label, .form-group label:not(.form-checkbox):not(.form-radio), 
.ce_form .widget:not(.widget-checkbox):not(.widget-radio) label:not(.form-checkbox):not(.form-radio) {
    background: #07639a;
}

.hero .hero-body {
    min-height: inherit;
    padding-bottom: 250px;
}

.hero .hero-body {
  background-image: url(/files/zeroOne/img/quote.svg);
}

**Comment by seibtph** [comment]
Have you reload the page with Strg + F5? Maybe it's a cache problem. The css should work.

**Comment by millerc-bmf** [comment]
Hi,
yes, different times. But does not work!

**Comment by millerc-bmf** [comment]
Do I need a script before the custom scss? Or should it work like this? Do you have any example scss file for testing?

**Comment by seibtph** [comment]
I tested this in our development environment and it works. The css should be inserted in the custom.scss.

The CSS is not loaded at all. Have you made any adjustments?

If this not works you can send a admin login from your website to support@pdir.de. Than we can check this problem.

**Comment by millerc-bmf** [comment]
Hi,

I have inserted this code in the custom.scss, but does not work. No other adjustment at the template, as I know are available.

Please find below the admin login for this page…

https://bmf-2022.de/contao
User: zero-one
PW: zero3980L#


Many thanks for your support
Christian

**Comment by seibtph** [comment]
I will check it. Please do not post your login information on Github, where everyone can see it (I have edited your last post).

**Comment by seibtph** [comment]
After clearing the script cache the scss was loaded.

**Comment by millerc-bmf** [comment]
Many thanks, but I think it does not work.
I changed the background image at the css, but its not available at the homepage.

This is the link to the background: https://bmf-2022.de/files/zeroOne/img/BMF/BMF2022_background-Logo_weichgezeichnet.jpg

Any other idea?

BR
Christian

**Comment by seibtph** [comment]
Do you use the Contao editor or do you edit the files via FTP? If you edit the files via FTP, you need to clear the script cache. After clearing the script cache the css works.

If you want to display the background image over the entire width and height, you need the following CSS.

```
.bg-sunrise.mod_article {
    background-image: url(/files/zeroOne/img/BMF/BMF2022_background-Logo_weichgezeichnet.jpg);
}

.hero .hero-body {
    background: none;
}
```

**Comment by millerc-bmf** [comment]
Perfect, many thanks!

I did not find the internal Contao editor. I used FTP…

BR
